### ISSUE TITLE
Warning issue in XCode 7

### ISSUE THREAD

**Issue by starlight173** [keygx/AlertHelperKit#1]
I updated from swift 1.2 to 2.0 and got 2 warnings:
AlertHelperKit.swift:116:48: Treating a forced downcast to 'UIBarButtonItem' as optional will never produce 'nil'
AlertHelperKit.swift:187:57: Forced cast of 'UIAlertAction' to same type has no effect

**Comment by keygx** [comment]
I merged the version that supported Swift 2.0 into a master branch.
Will you try it here?

**Comment by starlight173** [comment]
Thanks. The warning has gone away. You can close this issue now.

**Comment by keygx** [comment]
Welcome!
